name: Build Aplex APK

on: [push, workflow_dispatch]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Compile APK with Buildozer Cloud Engine
      uses: digreatbrian/buildozer-action@v2
      with:
        python-version: 3.11
        buildozer-cmd: yes | buildozer android debug

    - name: Upload Finished APK File
      uses: actions/upload-artifact@v4
      with:
        name: Aplex-Android-Package
        path: ./bin/*.apk
